### ISSUE TITLE
Incorrect typings for `getBacklinksForFile` and `CustomArrayDict`

### ISSUE THREAD

**Issue by mnaoumov** [Fevol/obsidian-typings#11]

**Comment by Fevol** [comment]
Many thanks for all the PR's, this one looks good to me! 

As a aside: apologies for all the errors I've made, I added most of these typings in a single evening - in a half sleep-deprived state. Currently I'm a bit low on time, but I'll try going over all of them as soon as I'm able (plus adding in the missing types on a lot of the workspace and editor-related components).

**Comment by mnaoumov** [comment]
Fixed in https://github.com/obsidian-typings/obsidian-typings/releases/tag/1.0.1
