### ISSUE TITLE
Consider publishing in NPM repository

### ISSUE THREAD

**Issue by mnaoumov** [Fevol/obsidian-typings#28]
All it takes is to run `npm publish`  and repeating it every time new release is ready.

This will improve discoverability of your amazing project.

**Comment by Fevol** [comment]
That's a very good suggestion, it would probably make it much more convenient to install. Here's the first release: https://www.npmjs.com/package/obsidian-typings

I've been trying to improve the experience of including the types a bit, I _think_ the three installation methods basically cover everything? Besides that, I've also added a short guide under [CONTRIBUTING.md](https://github.com/Fevol/obsidian-typings/blob/main/CONTRIBUTING.MD) that describes how to interface the different objects (through my lens, at least). 

Thank you again for all your PR's and suggestions, I am very unfamiliar with the npm ecosystem/correct typings, so I very much appreciate all your help.

**Comment by Fevol** [comment]
I will close this issue now as the NPM package should be fully completed now, thanks again for the suggestion!
