### ISSUE TITLE
MenuItem interface: Some methods should return MenuItem type

### ISSUE THREAD

**Issue by Acylation** [Fevol/obsidian-typings#40]
Thanks for gathering and maintaining these APIs!

I found and utilized `setWarning()` method to make menu item red. Usually these method should return itself after modification to allow chaining, and so does `setWarning()`. However its return is listed as void in this repo.

Example code:
```ts
const menu = new Menu();
menu.addItem((item) =>{  
       item.setTitle($i18n.t("components.tag.edit"))
        .setIcon("edit")
        .onClick((event) => {
            menu.close();
            dispatch("edit");
            event.stopPropagation();
            event.preventDefault();
        });
});
```

**Comment by Fevol** [comment]
Thanks, should be fixed now!
