### ISSUE TITLE
`Events.trigger` is overridden incorrectly with `Workspace.trigger`

### ISSUE THREAD

**Issue by NomarCub** [Fevol/obsidian-typings#41]
Here's a minimal example, that works without `obsidian-typings` but doesn't work with it included:

```ts
import { Menu, Plugin } from "obsidian";

export default class TestPlugin extends Plugin {
  test() {
    const menu = new Menu();
    this.app.workspace.trigger("", menu);
  }
}
```

![image](https://github.com/Fevol/obsidian-typings/assets/5298006/d7dc3fdd-b08f-4812-9849-cb674a84d274)

`trigger` now resolves to this (error: "Expected 1 arguments, but got two"):
![image](https://github.com/Fevol/obsidian-typings/assets/5298006/dc2bcfbb-cbf3-4b9a-805b-aa637f9d6815)

instead of this (works fine):
![image](https://github.com/Fevol/obsidian-typings/assets/5298006/aa38f61a-02b1-4e5e-988c-2c63155f800b)

**Comment by Fevol** [comment]
Thanks! In the `app.js` source code, there is a `trigger` function defined for every class that extends `Events`, which is generally given as single-parameter function:
```js
t.prototype.trigger = function(t) {
    for (var n = [], i = 1; i < arguments.length; i++)
        n[i - 1] = arguments[i];
    e.prototype.trigger.apply(this, w([t], n, !1))
}
```

And `w` given as:
```js
function w(e, t, n) {
    if (n || 2 === arguments.length)
        for (var i, r = 0, o = t.length; r < o; r++)
            !i && r in t || (i || (i = Array.prototype.slice.call(t, 0, r)),
        i[r] = t[r]);
    return e.concat(i || Array.prototype.slice.call(t))
}
```
In all honesty, I'm not really sure what these functions are doing specifically; my best guess is that they're mainly binding the context of `this` class to the `trigger` function of the `Events` prototype

For now, I've just commented these definitions, hopefully that is sufficient!

**Comment by Fevol** [comment]
I've now pushed these changes to version `1.0.6` on npm, let me know if that helps

**Comment by NomarCub** [comment]
It did solve it, thank you! 🙏
