### ISSUE TITLE
Does `revealInFolder` accept `TFile`s?

### ISSUE THREAD

**Issue by NomarCub** [Fevol/obsidian-typings#42]
This is the function: https://github.com/Fevol/obsidian-typings/blob/1.0.5/obsidian-ex.d.ts#L705

I'm converting my plugin to using obsidian-typings, and this line errored: https://github.com/NomarCub/obsidian-copy-url-in-preview/blob/1.6.0/src/main.ts#L327.

However, it worked in practice so far. Here `file` is the result of [`getFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L4080), and thus a `TFile`. I'd think `revealInFolder` accepts `TFolder | TFile` or even just `TFile` instead of `TFolder`.

**Comment by Fevol** [comment]
Yep, my bad! That should indeed be `TFile | TFolder`, and the function isn't async either. 
I've also added the `revealInFolder` definition for the file explorer view (which only reveals the file, it doesn't do any checks whether the leaf is in focus or visible)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/obsidian-typings/obsidian-typings/releases/tag/1.0.6
