### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by mnaoumov** [Fevol/obsidian-typings#6]
There are some syntax issues making typings invalid

**Comment by Fevol** [comment]
Thanks for the PR, I have added some comments about things I'm personally not entirely sure about. Would you mind quickly checking these?

**Comment by mnaoumov** [comment]
@Fevol I don't see the comments you are referring to

**Comment by Fevol** [comment]
They should be listed under the PR, though admittedly, I may have done something wrong -- this is the first time I've used this feature properly.
See here: https://github.com/Fevol/obsidian-typings/pull/7

**Comment by mnaoumov** [comment]
Fixed in https://github.com/obsidian-typings/obsidian-typings/releases/tag/1.0.1
