### ISSUE TITLE
Split up `obsidian-ex.d.ts` into separate files

### ISSUE THREAD

**Issue by Fevol** [Fevol/obsidian-typings#63]
Request from Discord, looking for opinions.

Currently the typings file is 5000 lines long, and isn't particularly easy to navigate through without dedicated search tools. It would be interesting to split up the typings file into logical chunks for easier lookup.

There are several ways this could be done.

First, how the divisions should be made:
- Split up according to inheritance, everything related to `View`, `Editor`, `Plugin` should be separated into individual files
- Split up according to type of functionality (all modals, all metadata, all workspace-related, etc.)
- ...

Second, whether the distributed typings (i.e. `npm` package) should bundle all these separate files together (so you can still search through a single `obsidian-ex.d.ts` file), or whether they should stay separated.

**Comment by mnaoumov** [comment]
@Fevol that's a brilliant idea! It would be helpful if you add the link to the Discord discussion to follow up.

Here is my input

1. Extract into individual files matching the augmented interfaces. Such as `obsidian/App.d.ts` and `@codemirror__view/EditorView.d.ts` (double underscore `__` is a standard convention to replace slash `/`) etc.
2. Don't put into `declare module "..."` axillary helpers that are not declared in the original module. For example, don't do

```typescript
declare module "obsidian" {
    interface InternalPlugins {}
}
```

because https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts doesn't define `InternalPlugins`

This helps to prevent confusion for the client code that can do

```typescript
import { InternalPlugins } from "obsidian";
```

which is confusing. I think forcing

```typescript
import { InternalPlugins } from "obsidian-typings";
```

has much clearer intent

3. I see no added value for the gigantic single `obsidian-ex.d.ts` file

**Comment by Fevol** [comment]
There isn't any discussion to link to, @4Source brought it up in a DM.
> 1. Extract into individual files matching the augmented interfaces. Such as obsidian/App.d.ts and @codemirror__view/EditorView.d.ts (double underscore __ is a standard convention to replace slash /) etc.

That sounds good!

> 2. Don't put into declare module "..." axillary helpers that are not declared in the original module. For example, don't do (...)

Agreed.

> 3. I see no added value for the gigantic single obsidian-ex.d.ts file

Since the package is usually installed in `node_modules`, it is usually excluded in the IDE search functionality. So if I for instance want to look for a specific class inside the typings, it is much easier to look through a single `obsidian-ex.d.ts` file than searching through each individual file. But that might also be something I can configure.

> 4. We should also make not only typings .d.ts but add some useful implementations in .ts, for example, CustomArrayDict interface would be useful with the sample implementation, for example https://github.com/mnaoumov/obsidian-backlink-cache/blob/master/src/CustomArrayDictImpl.ts

That's fine for me! I wonder if things like [`EmbeddableEditor`](https://github.com/Fevol/obsidian-criticmarkup/blob/main/src/ui/embeddable-editor.ts) would fit here too; or even further: some [useful developer functions](https://github.com/Fevol/obsidian-criticmarkup/blob/407222c6e981d7a2acda110f75fd1fcfd5113626/src/util/obsidian-util.ts#L22-L41). I'm not sure if this should be included into this package, or be branched off into its own package (e.g. `obsidian-dev-utils`)

**Comment by mnaoumov** [comment]
@Fevol as I already started drafting the PR for this issue I can provide more reasonable feedback

> if I for instance want to look for a specific class inside the typings

If you already know the type you want to augment, the navigation is pretty easy

![navigation](https://github.com/Fevol/obsidian-typings/assets/735878/eb469de4-ed3a-4eaa-be9b-e3e72b340ba2)

However, it seems that ChatGPT also into the gigantic one https://chatgpt.com/share/ba7a7d40-80cf-4aa5-8543-aac20848c8ef

> I'm not sure if this should be included into this package, or be branched off into its own package (e.g. obsidian-dev-utils)

I think the basic implementations of the interfaces is a good fit for this package. But the examples you provided are more suitable for the separate `obsidian-dev-utils` package. That would be an amazing package for general purpose helpers. I have tons of useful code snippets I use in my own plugins and scripts that other plugin developers could take advantage of.

**Comment by 4Source** [comment]
> 4. We should also make not only typings `.d.ts` but add some useful implementations in `.ts`, for example, `CustomArrayDict` interface would be useful with the sample implementation, for example https://github.com/mnaoumov/obsidian-backlink-cache/blob/master/src/CustomArrayDictImpl.ts

I think this might be confusing since the project is called obsidain-TYPINGS and adding additional features should be done separately in my opinion

> I think the basic implementations of the interfaces is a good fit for this package. But the examples you provided are more suitable for the separate `obsidian-dev-utils` package. That would be an amazing package for general purpose helpers. I have tons of useful code snippets I use in my own plugins and scripts that other plugin developers could take advantage of.

This would be a better fit in my opinion.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/obsidian-typings/obsidian-typings/releases/tag/2.0.0
