### ISSUE TITLE
Upgrade `@types/node`

### ISSUE THREAD

**Issue by unxok** [Fevol/obsidian-typings#81]
Amazing package, thank you for all of y'all's hard work!

I recently installed in a new project and got a dependency error on `@types/node`-- It appears you only allow versions `^16.11.6`, but some of my packages (vite, solidjs, etc.) require later versions. Is there any reason you can't upgrade your version? Or allow higher versions?

Honestly, I'm unsure of the significance of this (not super knowledgeable on package publishing), but I was able to `--force` my way through the install anyway, so I don't think it's a huge deal.

<details>
<summary>Show error log</summary>

```bash
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: obsidian-dataedit@0.0.0
npm error Found: @types/node@22.0.3
npm error node_modules/@types/node
npm error   dev @types/node@"^22.0.3" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @types/node@"^16.11.6" from obsidian-typings@2.0.0
npm error node_modules/obsidian-typings
npm error   dev obsidian-typings@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution
```
</details>

**Comment by Fevol** [comment]
Looking at the commit history, it seems like the `@types/node` version was chosen to match the sample-plugin version, I'd assume this is done to ensure that the package is compatible with plugins that have never updated the node typings. 

@mnaoumov Would you happen to know more?

**Comment by mnaoumov** [comment]
@Fevol yes, I did that for the sample plugin but I came up with the proper fix which I'm currently working on. Will be released shorty

**Comment by mnaoumov** [comment]
Fixed in https://github.com/obsidian-typings/obsidian-typings/releases/tag/2.1.3
