### ISSUE TITLE
Rename `activateTab` to `activeTab`

### ISSUE THREAD

**Issue by aandrejevas** [Fevol/obsidian-typings#88]
### Summary
Currently `activateTab` is defined like this:
![image](https://github.com/user-attachments/assets/3aa6946a-975e-4069-bab0-b958d968bfe2)

But actually this property is named `activeTab` and it seems that it is `null` when the settings modal is closed:
![image](https://github.com/user-attachments/assets/42ec6f02-0a61-4f37-9c33-372061a22468)

### What is to be done
Rename `activateTab` to `activeTab` and change the type to `SettingTab | null`. Suggestion:
```typescript
interface Setting extends Modal {
        // ...
        /**
         * Current active tab of the settings modal
         */
        activeTab: SettingTab | null;
        // ...
}
```

**Comment by mnaoumov** [comment]
Fixed in https://github.com/Fevol/obsidian-typings/releases/tag/2.2.1-beta.22
