### ISSUE TITLE
Enhanced Obsidian Template

### ISSUE THREAD

**Issue by mnaoumov** [Fevol/obsidian-typings#92]
For Your Information I've created a template that significantly accelerates the process of creating, modifying, and publishing Obsidian plugins on GitHub. This template incorporates obsidian-typings to enhance development capabilities.
After numerous iterations, the template has reached a highly refined state. However, I believe there's still considerable room for improvement. I created a new branch for Sass but I need to update it. I welcome any feedback, suggestions, or contributions to further enhance this template. I think it will be a good thing to do a repo with several possible base configurations.
https://github.com/3C0D/obsidian-sample-plugin-modif

_Originally posted by @3C0D in https://github.com/Fevol/obsidian-typings/issues/91#issuecomment-2403632149_

**Comment by mnaoumov** [comment]
@3C0D, I also built my own templates

https://github.com/mnaoumov/generator-obsidian-plugin
https://github.com/mnaoumov/obsidian-dev-utils

Maybe we can combine our efforts

**Comment by 3C0D** [comment]
Thanks for sharing. I guess it's much more advanced... but it will be cool thing a centralized place for more advanced templates
