### ISSUE TITLE
`Plugin` interface is renamed to `Plugin$1` and breaks stuff

### ISSUE THREAD

**Issue by unxok** [Fevol/obsidian-typings#97]
## Description of issue

It looks like the problem is with [dts-bundle-generator](https://github.com/timocov/dts-bundle-generator), but I couldn't find an existing issue that fully matches this problem.

It appears that the tool is renaming it to `Plugin$1` due to it detecting a conflict with the (deprecated) global [Plugin](https://developer.mozilla.org/en-US/docs/Web/API/Plugin). I'm guessing the tool detects the conflict and renames it in the assumption that the obsidian-typings' interface is meaning to extend the global interface or that you will export it with something (in which case it will export it correctly with its true name).

Due to this rename, typescript is only aware that `Plugin$1` extends the `Component` interface and not that it is supposed to be merged with the `Plugin` class from obsidian.

## Minimal repro
```ts
import { Plugin, PluginSettingTab } from "obsidian";

export default class MyPlugin extends Plugin {
  onload() {
    this.addSettingTab(new MySettingTab(this)) // type error: MySettingTab is incompatible with PluginSettingTab
  }
}

class MySettingTab extends PluginSettingTab {
  // type error: property "plugin" incompatible with known property from base type
  // because Plugin$1 is not merged with Plugin
  plugin: MyPlugin;
  constructor(plugin: MyPlugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
}
```

## Workaround
The easiest fix is just to replace all occurrences of "Plugin$1" with "Plugin" and remove the renaming of "Plugin" in the import statement within the `types.d.ts` file. Obviously this isn't preferred, but I'm guessing the true solution will take some time since it likely is dts-bundle-generator's problem.

**Comment by mnaoumov** [comment]
@unxok I don't see an issue with the code you provided.

Please prepare a full example including `package.json` and `tsconfig.json`

**Comment by unxok** [comment]
There isn't anything wrong with the code example I provided. 

The issue is obsidian-typings definition for "Plugin" is renamed to "Plugin$1" by dts-bundle-generator. Because of this, the code example I provided will have typescript errors.

**Comment by mnaoumov** [comment]
@unxok 

I don't have typescript errors with your code that's why I asked for a complete example

**Comment by unxok** [comment]
@mnaoumov 

Ah I see, then the easiest way to see a "complete" example would be just to look at my [repo](https://github.com/unxok/obsidian-better-properties) where it's happening and fork it?

Or would you rather I make an entire example plugin to demonstrate the error?

**Comment by mnaoumov** [comment]
@unxok I was finally able to reproduce the issue. Working on the fix

**Comment by mnaoumov** [comment]
Fixed in https://github.com/Fevol/obsidian-typings/releases/tag/2.2.1-beta.33

**Comment by mnaoumov** [comment]
Opened a corresponding issue https://github.com/timocov/dts-bundle-generator/issues/335

**Comment by mnaoumov** [comment]
Opened a corresponding issue https://github.com/timocov/dts-bundle-generator/issues/335

**Comment by unxok** [comment]
Nice thanks for that!
